// Generated by CoffeeScript 1.3.1
(function() {
  var BANNER, catData, cats, catsjs, fs, jquery, jsdom, parseOptions, path, prettyjson, printLine, printWarn, pullDataFromString, pullDataFromUrl, request, scraped, url, usage;

  fs = require('fs');

  path = require('path');

  jsdom = require('jsdom');

  request = require('request');

  prettyjson = require('prettyjson');

  jquery = fs.readFileSync("./lib/jquery.js").toString();

  catsjs = fs.readFileSync("./lib/cats.js").toString();

  printLine = function(line) {
    return process.stdout.write(line + '\n');
  };

  printWarn = function(line) {
    return process.stderr.write(line + '\n');
  };

  BANNER = 'Usage: dscrape cats-file url ';

  cats = [];

  catData = [];

  url = "";

  exports.run = function() {
    var cfile, contents, _i, _len;
    if (parseOptions()) {
      for (_i = 0, _len = cats.length; _i < _len; _i++) {
        cfile = cats[_i];
        contents = fs.readFileSync(cfile).toString();
        catData.push(contents);
      }
      return pullDataFromUrl(url, cats, scraped);
    }
  };

  scraped = function(data) {
    return printLine(prettyjson.render(data));
  };

  parseOptions = function() {
    var opts;
    opts = process.argv.slice(2);
    if (opts.length < 2) {
      printWarn("Not enough arguments");
      usage();
      return false;
    }
    cats.push(opts[0]);
    url = opts[1];
    return true;
  };

  pullDataFromUrl = function(theUrl, catsSheets, scraped) {
    return request({
      uri: theUrl
    }, function(error, response, body) {
      if (error && response.statusCode !== 200) {
        printWarn("Error contacting " + url);
        return {};
      }
      return pullDataFromString(body, catsSheets, scraped);
    });
  };

  pullDataFromString = function(str, catsSheets, scraped) {
    var data;
    data = {};
    return jsdom.env({
      html: str,
      src: [jquery, catsjs],
      done: function(err, window) {
        var engine, sheet, _i, _len;
        engine = new window.CATS.Engine();
        for (_i = 0, _len = catData.length; _i < _len; _i++) {
          sheet = catData[_i];
          window.CATS.Cascade.attachSheet(sheet);
        }
        console.log("Blocks__________________________");
        printLine(prettyjson.render(window.CATS.Cascade.blocks));
        console.log("");
        console.log("");
        data = engine.recoverData(window.$('html'));
        return scraped(data);
      }
    });
  };

  usage = function() {
    return printLine(BANNER);
  };

}).call(this);
